name: SimpleFly
main: SimpleFly.MainClass
version: "1.0.0"
api: ["1.0.0"]
load: POSTWORLD
author: Pub4Game. Translated by GoldRushCoding
description: Plugin adding a flight to your server.
commands:
   fly:
     description: Enables / Disables the flight.
     usage: "/ fly"
     permission: fly.command.fly

permissions:
   fly.command.fly:
     description: "Permits using the / fly command"
     default: op
